---
title: “Sta 323 - Introduction”
author: “Colin Rundel”
date: “2017-01-09”
output:
  xaringan::moon_reader:
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---

exclude: true

```{r, message=FALSE, warning=FALSE, include=FALSE}
```

---

## Policies

* Plagiarism
    + Use online resources but make sure to cite them
    + No direct code sharing between groups / individuals
* Homework
    + Group based, everyone is equally responsible
* Late work
    + late, but same day: -10%
    + late, next day:  -20%
    + 2 days or later: no credit
* Exams
    + 2 Midterms, take home

—-

## Grading


  Component      Percentage
-------------  --------------
Homework         50%
Midterm 1        20%
Midterm 2        20%
Final Project    10%

—-

## Groups

* Group homework assignments
    + Roughly biweekly assignments
    + Open ended
    + 10 - 20 hours of work each
    + Peer review at the end

* Expectations and roles
    + Everyone is expected to contribute equally
    + Everyone is expected to understand *all* code turned in
    + Individual contribution evaluated by peer assessment

—-

## Reproducible Research / Computing

* Unix shell

* R + RStudio

* rmarkdown + make

* Git + github

—-

## In the next couple days

* Create a github account
* Complete the course survey (email tonight)
* Install recommended [software](https://stat.duke.edu/~cr173/Sta523_Fa17/software/)
* Once I let you know (via email) try to login in to [saxon](http://saxon.stat.duke.edu:8787)

—-